name: npm publish
on: push
jobs:
  publishtonpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git branch
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build-lib
      - name: create npm rc file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH }}" >> .npmrc
