name: npm publish
on: push
jobs:
  publishtonpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git branch
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build-lib
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH }}" >> .npmrc
      - run: find . -name ".npmrc"
      - run: npm run publish-lib
